apiVersion: v1
kind: ServiceMonitor
metadata:
  name: chat-services
  namespace: chat-app
  labels:
    app: chat-application
spec:
  selector:
    matchLabels:
      app: chat-application
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: chat-app
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: chat-app
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: chat-app
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      isDefault: true
      editable: true
