server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      loadbalancer:
        enabled: false
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
        - id: chat-service
          uri: http://chat-service:8082
          predicates:
            - Path=/api/chat/**
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/api/notifications/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "https://yourdomain.com"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
        pool:
          max-connections: 500
          max-idle-time: 30s
          max-life-time: 60s
      metrics:
        enabled: true
        tags:
          application: ${spring.application.name}
    discovery:
      client:
        simple:
          instances:
            user-service:
              - uri: http://user-service:8081
            chat-service:
              - uri: http://chat-service:8082
            notification-service:
              - uri: http://notification-service:8083

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.chat.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway-service.log

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      chat-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      notification-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      websocket-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
      chat-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
      notification-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
